# Generated by Django 2.2.5 on 2020-01-16 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20200116_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
