# Generated by Django 2.2.5 on 2020-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_user_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='file_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
